# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
sudo: true
cache: packages
os:
- osx


install:
- Rscript travis_script.r

script:
- travis_wait R CMD build .
- travis_wait R CMD check *tar.gz --no-manual

