# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
sudo: true
cache: packages
os:
- osx
- linux

before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

install:
- Rscript travis_script.r

script:
- travis_wait R CMD build .
- travis_wait R CMD check *tar.gz --no-manual

